export { default as HomePage } from "./homepage";
export { default as AboutUs } from "./Aboutus/aboutus";
export { default as LoginPage } from "./login";
export { default as Error404 } from "./error404";
export { default as Contactos } from "./contactos";
export { default as Reservas } from "./reservas";
export { default as Cabanias } from "./cabanias";
export { default as Galeria } from "./galeria";
export { default as AdminPage } from "./adminPage";
